language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - yarn test
env:
  - CI=true

# Added revised yarn verbiage
before_deploy:
  - yarn global add netlify-cli
  - yarn run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master